//
//  NSColorPanel mib
//
{
    "Objects" = { 
		elements = ( "Color_Panel" ); 
		isa = NSMutableArray; 
	};

    "Color_Panel" = {
		isa = IMCustomObject;
		className = NSColorPanel;
		realObject = "ColorPanel";
    };

    "ColorPanel" = {
		backingType = 2;
		contentView = "ColorPanelView";
		frame = "{x = 200; y = 200; width = 200; height = 250}";
		isVisible = YES;
		level = 0;
		isa = NSColorPanel;
		isAutodisplay = NO;
		title = "Colors";
		isDocumentEdited = NO;
		representedFilename = "";
		isReleasedWhenClosed = NO;
		delegate = nil;
		prompt = "Name:";
		accessoryView = nil;
		requiredFileType = "";
		treatsFilePackagesAsDirectories = YES;
		directory = ".";
		styleMask = 3; 
   };

    "ColorPanelView" = {
		autoresizesSubviews = YES;
		autoresizingMask = 0;
		bounds = "{x = 0; y = 0; width = 200; height = 250}";
		frame = "{x = 0; y = 0; width = 200; height = 250}";
		isa = NSView;
		nextResponder = "ColorPanel";
		postBoundsChangedNotifications = YES;
		postFrameChangedNotifications = YES;
		subviews = "ColorPanelSubviews";
		superview = nil;
		tag = 0;
		};

    "ColorPanelSubviews" = {
		elements = (
				"ImageView",
				"ColorWell",
				"MagnifierButton");
		isa = NSMutableArray;
    };

    "ColorWell" = {
		autoresizesSubviews = NO;
		autoresizingMask = 8; 
		bounds = "{x = 0; y = 0; width = 125; height = 30}";
		frame = "{x = 70; y = 215; width = 125; height = 30}";
		isBordered = NO;
		isa = NSColorWell;
		nextResponder = "ColorPanelView";
		postsBoundsChangedNotifications = YES;
		postsFrameChangedNotifications = YES;
		color = nil;
		subviews = nil;
		superview = "ColorPanelView";
	};

    "MagnifierButton" = {
		alignment = 2;
		alternateImage = nil;
		alternateTitle = "";
		autoresizesSubviews = NO;
		autoresizingMask = 1;
		bounds = "{x = 0; y = 0; width = 60; height = 30}";
		frame = "{x = 5; y = 215; width = 60; height = 30}";
		delay = 0.2;
		highlightsBy = 14;
		ignoresMultiClick = NO;
		image = nil;
		imagePosition = 1;
		interval = 0.025;
		isBordered = YES;
		isContinuous = NO;
		isEnabled = YES;
		isTransparent = NO;
		isa = NSButton;
		keyEquivalent = "";
		nextResponder = "ColorPanelView";
		postsBoundsChangedNotifications = YES;
		postsFrameChangedNotifications = YES;
		showsStateBy = 0;
		state = 0;
		subviews = nil;
		superview = "ColorPanelView";
		tag = 0;
		title = "";
		};

    "ImageView" = {
		alignment = 2;
		autoresizesSubviews = NO;
		autoresizingMask = 8; 
		bounds = "{x = 0; y = 0; width = 159; height = 159}";
		frame = "{x = 10; y = 40; width = 159; height = 159}";
		ignoresMultiClick = NO;
		image = nil;
		imagePosition = 1;
		isBordered = NO;
		isa = NSImageView;
		keyEquivalent = "";
		nextResponder = "ColorPanelView";
		postsBoundsChangedNotifications = YES;
		postsFrameChangedNotifications = YES;
		showsStateBy = 0;
		state = 0;
		subviews = nil;
		superview = "ColorPanelView";
		tag = 0;
		title = "";
	};

    "Connections" = { 
        elements = (); 
		isa = NSMutableArray;
    };

    RootObject = {Connections="Connections"; Objects="Objects"; isa=GMModel; }; 
    TopLevelObjects = (RootObject);
    Version = 1;
};
