// Generated by the WebObjects Wizard
#import "Application.h"

@implementation Application

- init {
    self = [super init];
    if (self) {
        /* ** put your initialization code in here ** */
    }
    return self;
}

- (void)dealloc {
    // If you add any ivars you may want to add [ivar release] here to avoid leaks.
    [super dealloc];
}

@end
