// Generated by the WebObjects Wizard
#import "DirectAction.h"
#import <WebObjects/WOComponent.h>

@implementation DirectAction : WODirectAction 

- (WOComponent *)defaultAction {
    return [self pageWithName:@"Main"];
}

@end
