// Generated by the WebObjects Wizard Mon Apr 10 10:55:52 CET 2000

#import "Main.h"

@implementation Main


- (void)dealloc {
    // If you add any ivars you may want to add [ivar release] here to avoid leaks.
    
    [super dealloc];
}

@end
