// Generated by the WebObjects Wizard

#import "Session.h"

@implementation Session

- (void)dealloc {
    // If you add any ivars you may want to add [ivar release] here to avoid leaks.
    [super dealloc];
}

@end
