#!/bin/sh

# Copyright (c) 1997-2005, Sen:te (Sente SA).  All rights reserved.
#
# Use of this source code is governed by the following license:
# 
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
# 
# (1) Redistributions of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.
# 
# (2) Redistributions in binary form must reproduce the above copyright notice, 
# this list of conditions and the following disclaimer in the documentation 
# and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
# IN NO EVENT SHALL Sente SA OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# Note: this license is equivalent to the FreeBSD license.
# 
# This notice may not be removed from this file.


if [ "$TEST_AFTER_BUILD" = "YES" ]; then

    if [ "X$OTEST" = "X" ]; then
    	OTEST=~/Developer/Tools/otest
    fi

    if [ "$WRAPPER_EXTENSION" ]; then
        OTEST_TARGET=$SYMROOT/$PRODUCT_NAME.$WRAPPER_EXTENSION
    else
        OTEST_TARGET=$SYMROOT/$PRODUCT_NAME
    fi
#
#    echo $OTEST $OTEST_TARGET
#    echo "BUILT_PRODUCTS_DIR  = $BUILT_PRODUCTS_DIR"
#    echo "DYLD_LIBRARY_PATH  = $DYLD_LIBRARY_PATH"
#
    if [ "X$BUILT_PRODUCTS_DIR" = "X" ] ; then \
	$OTEST "${OTEST_TARGET}"
    else
	if [ "X$DYLD_LIBRARY_PATH" = "X" ] ; then \
		env DYLD_FRAMEWORK_PATH="$BUILT_PRODUCTS_DIR" $OTEST "${OTEST_TARGET}"
	else
		env DYLD_FRAMEWORK_PATH="$BUILT_PRODUCTS_DIR:$DYLD_LIBRARY_PATH" $OTEST "${OTEST_TARGET}"
	fi
    fi
#    echo "DYLD_FRAMEWORK_PATH  = $DYLD_FRAMEWORK_PATH"
fi
